# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a970798b77e9b2c45d5eddba41480b85c5c9d235302fc62a491175dbf23c63648b94838da4cf63537d9dfc9319fb68f3aadb3f27db829ed5b9ff3908f31bdaf

test:
  secret_key_base: e043ad1feeb7a614450618c941b6e4c625c704037098501975464688d55c1524326b27576b8107bec8e8c2501e3446515ccd0410bf60a22b2ecaaa886aa731e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
